### ISSUE TITLE
404 Not found error on download.oracle.com

### ISSUE THREAD

**Issue by akshayakhanna** [jpnewman/ansible-role-java#7]
i am trying to install java on ubuntu-16.04 but get following error:

http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz

302 Moved Temporarily\r\nLocation: https://edelivery.oracle.com/otn-pub/java/
jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz

302 Moved Temporarily\r\nLocation: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516248471_ce03e11197a699e0ee273
b0022d11002 [following]\r\n--2018-01-18 04:05:51--  http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516248471_ce03e11197a699e0ee273b0022d11002\r\nConnect
ing to download.oracle.com (download.oracle.com)|23.53.157.169|:80... connected.\r\nHTTP request sent, awaiting response... 404 Not Found

is this something broken at Oracle end ?

Please note that this role was working around 2 weeks back.

**Comment by btrajkovski** [comment]
Yes oracle removed version 151 because version 162 is latest today. `web8upd` repostiory still uses 151 version and builds started to fail from today. More info and work arounds here: https://stackoverflow.com/questions/48318832/unable-to-install-java8-using-ppa-repository-on-ubuntu-16-04/48329603#48329603

**Comment by jpnewman** [comment]
Hi Akshay,

Bojan is correct. Seeing as this role currently relies on the webupd8team PPA, this issue should be resolved once it has been updated. However, to better support this scenario in the future I'll update this role to optionally download and install Java from a URL.

Regards,
John Paul.

**Comment by jpnewman** [comment]
Hi Akshay,

It looks like the webupd8 PPA has been updated and therefore this role should work again.

I've also committed version 1.1.0 of this role which supports installing Oracle Java from webupd8 PPA, URL direct download and local files. As well as support for OpenJDK.

Hope this helps?

Regards,
John Paul.

**Comment by akshayakhanna** [comment]
Thank you so much John.
